name: "site"

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-python@v2

      - run: npm install

      - run: npm run build-css

      - run: |
          pip3 install -r requirements.txt
          ./scripts/gen_pages.py

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: site-dist # The folder the action should deploy.
